version: '3.8'

services:
  telegram_poster:
    build: .
    container_name: telegram_poster
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - CRON_SCHEDULE=0 10,15 * * *
      #- HTTP_PROXY=
      #- HTTPS_PROXY=
      #- NO_PROXY=localhost,127.0.0.1
    volumes:
      - ./.env:/app/.env:ro
      - ./logs/telegram_poster.log:/var/log/telegram_poster.log
      - ./story_state.json:/app/story_state.json
    # Если нужно пробросить порты, раскомментируйте следующую строку
    # ports:
    #   - "8080:8080"
